---
- name: Configure Docker host
  hosts: all
  become: true  # Run commands with sudo
  gather_facts: yes

  tasks:
    # Install required packages
    - name: Install dependencies
      yum:
        name:
          - docker
          - python3-pip
        state: present
      tags: install

    # Start and enable Docker service
    - name: Ensure Docker is running
      service:
        name: docker
        state: started
        enabled: yes
      tags: service

    # Install Docker Python SDK
    - name: Install Docker Python module
      pip:
        name: docker
        executable: pip3
      tags: pip

    # Add ec2-user to docker group
    - name: Add user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes
      tags: users

    # Pull Nginx image
    - name: Pull Nginx container image
      docker_image:
        name: nginx:alpine
        source: pull
      tags: docker

    # Run Nginx container
    - name: Launch Nginx container
      docker_container:
        name: webserver
        image: nginx:alpine
        ports:
          - "80:80"
        restart_policy: always
        state: started
      tags: deploy