---
- name: Install Docker on Amazon Linux 2
  hosts: servers
  become: yes
  vars:
    docker_user: "ec2-user"

  pre_tasks:
    - name: Check if Python 3.8 exists
      stat:
        path: /usr/bin/python3.8
      register: python38_check
      tags: python

    - name: Install Python 3.8 if missing
      block:
        - name: Install prerequisites for Python 3.8
          yum:
            name:
              - gcc
              - openssl-devel
              - bzip2-devel
              - libffi-devel
              - zlib-devel
              - make
            state: present
          tags: python

        - name: Download Python 3.8 source
          get_url:
            url: https://www.python.org/ftp/python/3.8.18/Python-3.8.18.tgz
            dest: /tmp/Python-3.8.18.tgz
          tags: python

        - name: Extract Python source
          unarchive:
            src: /tmp/Python-3.8.18.tgz
            dest: /tmp
            remote_src: yes
          tags: python

        - name: Compile and install Python 3.8
          command: |
            cd /tmp/Python-3.8.18
            ./configure --enable-optimizations
            make altinstall
          args:
            creates: /usr/local/bin/python3.8
          tags: python

        - name: Create symlink for system Python 3.8
          file:
            src: /usr/local/bin/python3.8
            dest: /usr/bin/python3.8
            state: link
            force: yes
          tags: python
      when: not python38_check.stat.exists
      tags: python

    - name: Set Python 3.8 as default alternative
      command: alternatives --set python /usr/bin/python3.8
      when: not python38_check.stat.exists
      tags: python

    - name: Verify Python is available
      setup:
      tags: python

  tasks:
    - name: Update all packages
      yum:
        name: '*'
        state: latest
      tags: packages

    - name: Install required system packages
      yum:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
        state: present
      tags: packages

    - name: Add Docker repository
      command: amazon-linux-extras enable docker
      changed_when: false
      tags: docker

    - name: Install Docker
      yum:
        name: docker
        state: present
        disable_gpg_check: yes
      register: docker_install
      ignore_errors: yes
      tags: docker

    - name: Ensure Docker is installed (fallback)
      raw: amazon-linux-extras install -y docker || yum install -y docker
      when: docker_install is failed
      changed_when: "'already installed' not in docker_install.stdout"
      tags: docker

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes
      tags: docker

    - name: Add user to docker group
      user:
        name: "{{ docker_user }}"
        groups: docker
        append: yes
      tags: docker

    - name: Install Docker Compose (v2)
      block:
        - name: Create Docker CLI plugins directory
          file:
            path: /usr/local/lib/docker/cli-plugins
            state: directory
            mode: '0755'

        - name: Download Docker Compose
          get_url:
            url: https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64
            dest: /usr/local/lib/docker/cli-plugins/docker-compose
            mode: '0755'
            owner: root
            group: root
      tags: docker-compose

    - name: Verify Docker installation
      command: docker --version
      register: docker_version
      changed_when: false
      tags: verify

    - name: Verify Docker Compose installation
      command: docker compose version
      register: docker_compose_version
      changed_when: false
      tags: verify

    - name: Show Docker versions
      debug:
        msg:
          - "Docker version: {{ docker_version.stdout }}"
          - "Docker Compose version: {{ docker_compose_version.stdout }}"
      tags: verify