AWSTemplateFormatVersion: "2010-09-09"
Description: "Auto-deployable web server with VPC, EC2, and ECR"

Parameters:
  KeyPairName:
    Type: "AWS::EC2::KeyPair::KeyName"
    Description: "Name of your EC2 key pair (e.g., 20058324_key_pair)"
    Default: "20058324_key_pair"

  LatestAmiId:
    Type: "AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>"
    Description: "Latest Amazon Linux 2 AMI"
    Default: "/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2"

Resources:
  # 1. Networking
  VPC:
    Type: "AWS::EC2::VPC"
    Properties:
      CidrBlock: "10.0.0.0/16"
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: "Name"
          Value: "WebApp-VPC"

  InternetGateway:
    Type: "AWS::EC2::InternetGateway"
    Properties:
      Tags:
        - Key: "Name"
          Value: "WebApp-IGW"

  GatewayAttachment:
    Type: "AWS::EC2::VPCGatewayAttachment"
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  PublicSubnet:
    Type: "AWS::EC2::Subnet"
    Properties:
      VpcId: !Ref VPC
      CidrBlock: "10.0.1.0/24"
      AvailabilityZone: !Select [0, !GetAZs ""] # Modify if required
      MapPublicIpOnLaunch: true
      Tags:
        - Key: "Name"
          Value: "Public-Subnet"

  RouteTable:
    Type: "AWS::EC2::RouteTable"
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: "Name"
          Value: "Public-RouteTable"

  PublicRoute:
    Type: "AWS::EC2::Route"
    DependsOn: GatewayAttachment
    Properties:
      RouteTableId: !Ref RouteTable
      DestinationCidrBlock: "0.0.0.0/0"
      GatewayId: !Ref InternetGateway

  SubnetRouteTableAssociation:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      SubnetId: !Ref PublicSubnet
      RouteTableId: !Ref RouteTable

  # 2. Security
  WebServerSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Allow HTTP (port 3000) and SSM"
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: "tcp"
          FromPort: 3000
          ToPort: 3000
          CidrIp: "0.0.0.0/0"  # Allow HTTP traffic on port 3000
        - IpProtocol: "tcp"
          FromPort: 22
          ToPort: 22
          CidrIp: "0.0.0.0/0"  # Allow SSH access, if needed (for troubleshooting)
      Tags:
        - Key: "Name"
          Value: "WebServer-SG"

  # 3. IAM Role for EC2
  EC2Role:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: ["ec2.amazonaws.com"]
            Action: ["sts:AssumeRole"]
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly"
        - "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore"  # Ensure EC2 instance can use SSM
        - "arn:aws:iam::aws:policy/AmazonEC2FullAccess"  # Ensure EC2 has necessary permissions (optional)

  EC2InstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Roles: [!Ref EC2Role]

  # 4. EC2 Instance
  WebServer:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: !Ref LatestAmiId
      InstanceType: "t2.micro"
      KeyName: !Ref KeyPairName
      IamInstanceProfile: !Ref EC2InstanceProfile
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          GroupSet: [!Ref WebServerSecurityGroup]
          SubnetId: !Ref PublicSubnet
      UserData:
        Fn::Base64: |
          #!/bin/bash
          yum update -y
          amazon-linux-extras install docker -y
          systemctl enable docker
          systemctl start docker
          usermod -aG docker ec2-user
          # Generate host keys for SSH fingerprint (if SSM is not used to connect)
          ssh-keygen -A > /dev/null 2>&1
          # Pull the Docker image from ECR and run the container
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ AWS::AccountId }}.dkr.ecr.${AWS::Region}.amazonaws.com/webapp
          docker run -d -p 3000:3000 --name webapp ${{ AWS::AccountId }}.dkr.ecr.${AWS::Region}.amazonaws.com/webapp:latest
      Tags:
        - Key: "Name"
          Value: "WebServer"

  # 5. ECR Repository
  AppRepository:
    Type: "AWS::ECR::Repository"
    Properties:
      RepositoryName: "webapp"
      ImageTagMutability: "MUTABLE"
      ImageScanningConfiguration:
        ScanOnPush: true

Outputs:
  EC2PublicIP:
    Description: "Web Server Public IP"
    Value: !GetAtt WebServer.PublicIp
  EC2PublicDNS:
    Description: "Web Server Public DNS"
    Value: !GetAtt WebServer.PublicDnsName
  ECRRepositoryURI:
    Description: "ECR Repository URI"
    Value: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/webapp"